apiVersion: v1
kind: Service
metadata:
  name: recommender-api-service
spec:
  selector:
    app: bernardo-recommender # Procura pods com esta label
  ports:
    - protocol: TCP
      port: 50002
      targetPort: 50002