apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bernardo-pvc
spec:
  storageClassName: default-storage-class-bernardooliveira
  accessModes:
    - ReadWriteMany # Permite que vários pods leiam e escrevam
  resources:
    requests:
      storage: 1Gi # 1GB de espaço
  selector:
    matchLabels:
      namespace: bernardooliveira